libnyanpasu/clash-nyanpasu

scripts/updater.mjs
This reverts commit a8c74e39c210d5259312fefea63e5a8f20ebab42.
Close #3
=> Revert "chore: remove un supported platform"

src-tauri/src/core/tray.rs
=> feat: add tooltip for tray

scripts/check.ts
Clash.Meta已解除归档，同时改名mihomo，更换下载链接为最新的仓库地址和版本
=> feat: update new clash.meta close #20

backend/tauri/src/cmds.rs, backend/tauri/src/config/profiles.rs, backend/tauri/src/main.rs, package.json, pnpm-lock.yaml, src/components/profile/profile-item.tsx, src/pages/profiles.tsx, src/services/cmds.ts
#34  support drag profile item, thanks to Pylogmon
=> feat: support drag profile item

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
* and try to trigger renovate scan
=> chore: update issues template

.stylelintrc.js, backend/Cargo.lock, backend/tauri/Cargo.toml, backend/tauri/src/cmds.rs, backend/tauri/src/config/clash.rs, backend/tauri/src/core/clash_api.rs, backend/tauri/src/core/core.rs, backend/tauri/src/main.rs, src/components/base/base-dialog.module.scss, src/components/base/base-dialog.tsx, src/services/api.ts, src/services/cmds.ts, src/services/delay.ts
* 固定 `runas` 到 `1.0.0`，修复：https://github.com/mitsuhiko/rust-runas/issues/13
* 移植：https://github.com/zzzgydi/clash-verge/commit/5a0fed9c93653f666e7b3293498ae2d2259cc907 ，解决：https://github.com/keiko233/clash-nyanpasu/issues/98
* 移植 https://github.com/zzzgydi/clash-verge/pull/850 ，修复 https://github.com/keiko233/clash-nyanpasu/issues/60
* 修复 dialog 垂直居中，以及 overflow 问题。
=> fix: issues

src/components/profile/editor-viewer.tsx, src/components/profile/profile-item.tsx, src/components/profile/profile-more.tsx, src/components/profile/profile-viewer.tsx, src/components/providers/rules-provider.tsx, src/components/setting/mods/clash-core-viewer.tsx, src/components/setting/mods/clash-field-viewer.tsx, src/components/setting/mods/clash-port-viewer.tsx, src/components/setting/mods/controller-viewer.tsx, src/components/setting/mods/hotkey-viewer.tsx, src/components/setting/mods/layout-viewer.tsx, src/components/setting/mods/misc-viewer.tsx, src/components/setting/mods/service-viewer.tsx, src/components/setting/mods/sysproxy-viewer.tsx, src/components/setting/mods/tasks-viewer.tsx, src/components/setting/mods/theme-viewer.tsx, src/components/setting/mods/update-viewer.tsx, src/components/setting/mods/web-ui-viewer.tsx, src/components/setting/setting-clash.tsx, src/components/setting/setting-verge.tsx, src/hooks/use-notification.ts, src/pages/_layout.tsx, src/pages/profiles.tsx, src/pages/providers.tsx, src/pages/settings.tsx, src/services/cmds.ts
while notification premission not granted, falling back to MUI notification.
close #247
=> fix: notification fallback

src/utils/shiki.ts
close https://github.com/keiko233/clash-nyanpasu/issues/264
=> fix(vite): rm useless shikiji langs support

backend/sysproxy-rs/src/macos.rs, backend/sysproxy-rs/src/windows.rs, backend/tauri/src/cmds.rs, backend/tauri/src/config/mod.rs, backend/tauri/src/config/prfitem.rs, backend/tauri/src/core/core.rs, backend/tauri/src/core/tasks/events.rs, backend/tauri/src/core/tasks/jobs/logger.rs, backend/tauri/src/core/tasks/jobs/profiles.rs, backend/tauri/src/core/tasks/storage.rs, backend/tauri/src/core/tasks/task.rs, backend/tauri/src/core/updater.rs, backend/tauri/src/core/win_service.rs, backend/tauri/src/enhance/mod.rs, backend/tauri/src/feat.rs, backend/tauri/src/utils/candy.rs, backend/tauri/src/utils/config.rs, backend/tauri/src/utils/dirs.rs, backend/tauri/src/utils/init.rs, backend/tauri/src/utils/mod.rs, backend/tauri/src/utils/resolve.rs
* improve UX intended to reeduce the impact on https://github.com/keiko233/clash-nyanpasu/issues/260
=> fix(updater):  should use nyanpasu proxy or system proxy when performing request

.github/workflows/daily.yml, .github/workflows/dev.yaml, .github/workflows/puiblish.yml, .github/workflows/release.yml, backend/tauri/overrides/nightly.conf.json, renovate.json, scripts/generate-latest-version.ts, scripts/publish.ts
close: https://github.com/keiko233/clash-nyanpasu/issues/265
=> feat: new release workflow

.github/workflows/daily.yml, backend/tauri/src/config/prfitem.rs, backend/tauri/src/enhance/mod.rs
close: https://github.com/keiko233/clash-nyanpasu/issues/306
=> fix: use if let instead

backend/tauri/src/core/win_uwp.rs, backend/tauri/src/utils/init.rs, backend/tauri/src/utils/resolve.rs, scripts/updater-nightly.ts
* Close https://github.com/keiko233/clash-nyanpasu/issues/351
=> fix: resources missing

backend/tauri/templates/installer.nsi
Close https://github.com/keiko233/clash-nyanpasu/issues/291
=> fix(nsis): kill nyanpasu processes while updating

backend/tauri/src/utils/dialog.rs, backend/tauri/src/utils/dirs.rs, backend/tauri/src/utils/init.rs
Will fix #409 
请检查下init.rs里面L92开始的处理是否妥当
=> feat(config): add migration for old config dir

.gitignore, backend/Cargo.lock, backend/tauri-plugin-deep-link/.github/workflows/audit.yml, backend/tauri-plugin-deep-link/.github/workflows/format.yml, backend/tauri-plugin-deep-link/.github/workflows/lint.yml, backend/tauri-plugin-deep-link/.github/workflows/release.yml, backend/tauri-plugin-deep-link/.gitignore, backend/tauri-plugin-deep-link/CHANGELOG.md, backend/tauri-plugin-deep-link/Cargo.toml, backend/tauri-plugin-deep-link/LICENSE_APACHE-2.0, backend/tauri-plugin-deep-link/LICENSE_MIT, backend/tauri-plugin-deep-link/README.md, backend/tauri-plugin-deep-link/cliff.toml, backend/tauri-plugin-deep-link/example/Info.plist, backend/tauri-plugin-deep-link/example/main.rs, backend/tauri-plugin-deep-link/renovate.json, backend/tauri-plugin-deep-link/src/lib.rs, backend/tauri-plugin-deep-link/src/linux.rs, backend/tauri-plugin-deep-link/src/macos.rs, backend/tauri-plugin-deep-link/src/template.desktop, backend/tauri-plugin-deep-link/src/windows.rs, backend/tauri/Cargo.toml, backend/tauri/Info.plist, backend/tauri/src/main.rs, src/components/profile/profile-viewer.tsx, src/pages/_layout.tsx, src/pages/profiles.tsx
=> feat: custom schema support

backend/Cargo.lock, backend/tauri/Cargo.toml, backend/tauri/src/core/tray/icon.rs, backend/tauri/src/core/tray/mod.rs, backend/tauri/src/main.rs, backend/tauri/src/utils/help.rs
Close https://github.com/LibNyanpasu/clash-nyanpasu/issues/188, https://github.com/LibNyanpasu/clash-nyanpasu/issues/99
=> feat(tray): add tray icon resize logic to improve icon rendering

backend/tauri/src/config/nyanpasu/mod.rs, backend/tauri/src/core/tray/mod.rs, backend/tauri/src/core/tray/proxies.rs, backend/tauri/src/feat.rs, src/components/setting/mods/misc-viewer.tsx, src/locales/en.json, src/locales/ru.json, src/locales/zh.json, src/services/types.d.ts
=> feat(backend): allow to hide tray selector

backend/tauri/src/cmds.rs
fix https://github.com/LibNyanpasu/clash-nyanpasu/issues/625
=> fix(cmds): migrate custom app dir typo

backend/tauri/src/enhance/merge.rs, backend/tauri/src/enhance/mod.rs
Close https://github.com/LibNyanpasu/clash-nyanpasu/issues/554
=> fix(chains): only guard fields should be overwritten

backend/tauri/src/core/updater.rs
dev branch seems to be abandoned.
=> Fetch version.json from main branch

frontend/nyanpasu/src/components/profiles/modules/side-chain.tsx
Just a simple typo fix. `New Chian` -> `New Chain`
=> fix(string): typo in side-chain.tsx

frontend/ui/materialYou/components/sidePage/style.module.scss
=> fix: left container scrollbar gutter

backend/webview2-com-bridge/Cargo.toml
Reverts LibNyanpasu/clash-nyanpasu#1228
=> chore: revert"fix(deps): update rust crate webview2-com to 0.32"

backend/Cargo.lock
Reverts LibNyanpasu/clash-nyanpasu#1314
=> Revert "fix(deps): update rust crate oxc_parser to v0.23.1"

frontend/nyanpasu/src/components/setting/modules/tray-icon-dialog.tsx
=> chore(i18n): tray icon dialog title i18n

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yaml
Fix typos, unify the typesetting style, fix some descriptions that do not match the actual situation, and fix some links.
=> docs: revise issue template [skip ci]

README.md
=> docs: revise readme [skip ci]

frontend/nyanpasu/src/components/setting/setting-system-service.tsx, frontend/nyanpasu/src/locales/en.json, frontend/nyanpasu/src/locales/ru.json, frontend/nyanpasu/src/locales/zh.json
cc @keiko233 @greenhat616 @4o3F
=> fix(i18n): system service setting prompt button i18n

frontend/nyanpasu/src/components/connections/connections-table.tsx
I forgot to notice this in the PR for impl zh-tw.
=> fix(i18n): connections table i18n for zh-tw

frontend/nyanpasu/src/components/profiles/profile-dialog.tsx, frontend/nyanpasu/src/components/setting/setting-clash-web.tsx, frontend/nyanpasu/src/components/setting/setting-system-proxy.tsx, frontend/nyanpasu/src/locales/en.json, frontend/nyanpasu/src/locales/ru.json, frontend/nyanpasu/src/locales/zh-CN.json, frontend/nyanpasu/src/locales/zh-TW.json
resolve https://github.com/libnyanpasu/clash-nyanpasu/issues/2529
=> feat(i18n): translate time units and dialog buttons

backend/tauri/src/shutdown_hook.rs, frontend/nyanpasu/package.json, frontend/nyanpasu/src/components/connections/connections-column-filter.tsx, frontend/nyanpasu/src/components/profiles/modules/chain-item.tsx, frontend/nyanpasu/src/components/profiles/profile-item.tsx, package.json
Resolve: https://github.com/libnyanpasu/clash-nyanpasu/issues/2626
=> fix(shutdown): windows panic

backend/tauri/src/core/clash/mod.rs
=> fix: avoid crash while using clash-rs

frontend/interface/tsconfig.json, frontend/ui/package.json, frontend/ui/vite.config.ts
The current solution may cause potential problem. I hope that professionals with more plentiful  expertise will offer even more refined solutions.
=> fix: solve the navigating to the definition in vscode

backend/tauri/src/config/nyanpasu/mod.rs, backend/tauri/src/core/tray/mod.rs, backend/tauri/src/feat.rs, frontend/interface/src/ipc/bindings.ts, frontend/interface/src/service/types.ts
This reverts commit 34132851f2f59dd813cd831b35910e0d956fe503.
=> Revert "feat: add enable_tray_text option (#3648)"

backend/tauri/src/utils/downloader.rs, frontend/nyanpasu/src/utils/parse-traffic.ts
=> fix: kernel download write display

frontend/nyanpasu/src/components/setting/setting-nyanpasu-path.tsx, frontend/nyanpasu/src/locales/en.json, frontend/nyanpasu/src/locales/ru.json, frontend/nyanpasu/src/locales/zh-CN.json, frontend/nyanpasu/src/locales/zh-TW.json
=> chore: adjust description

frontend/nyanpasu/src/store/index.ts
=> fix(route-memory): restore last visited page on window reopen
