scripts/check.mjs, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/cmds.rs, src-tauri/src/core/mod.rs, src-tauri/src/core/win_uwp.rs, src-tauri/src/main.rs, src/components/setting/setting-clash.tsx, src/locales/en.json, src/locales/ru.json, src/locales/zh.json, src/services/cmds.ts
1. 添加了内置UWP loopback修改工具的支持，类似CFW同功能
2. 目前版本在非管理员身份下运行时，安装服务会报错，但实际已经安装成功了。Debug确定是由于runas 1.1.0版本错误返回了exit code导致的，降级到1.0.0可解决。
参考runas的issue https://github.com/mitsuhiko/rust-runas/issues/13
=> feat: Add UWP tool support, fix install service bug

.github/workflows/dev.yaml
* 将 Dev 发布使用的 tag 修改为 `pre-release`
* 由 push 触发，修改成每日构建；配合手动触发，应该足够使用。
* 考虑到前端的库更新非常频繁，每日可能会有多个依赖更新被自动合并进去，非常浪费 CI 资源以及时间资源。
* 或许可以加一个 build 测试？
有必要给 dev 单独做一个 updater json，方便使用这个 channel 的也能享受每日的自动更新？ 
以及，文档是准备本仓库的 docs 存放，还是另开个仓库？
=> fix: dev build

manifest/version.json, package.json, pnpm-lock.yaml, scripts/check.ts, src/components/base/base-dialog.tsx, src/components/layout/layout-traffic.tsx, src/components/log/log-item.module.scss, src/components/log/log-item.tsx, src/components/providers/rules-provider.tsx, src/components/proxy/proxy-item-mini.tsx, src/components/proxy/proxy-item.tsx, src/components/setting/mods/clash-core-viewer.tsx, src/components/setting/mods/controller-viewer.tsx, src/locales/en.json, src/locales/ru.json, src/locales/zh.json, src/pages/_routers.tsx, src/pages/providers.tsx, src/services/api.ts, src/services/delay.ts, src/utils/shiki.ts
* fix: #124 
* 修复 mihomo alpha 内核的架构模板——解决更新器更新失败问题
* 修复 clash-verge-service 不能支持alpha内核以及rs内核的问题
* 使用 `shikiji` 处理日记结果 —— `ansi` 颜色文字能被正确渲染
* 对话框动画使用 `framer-motion`。
* 切换内核现在拥有动画了，且实现了锁。
* 修改端口和 secret 现在 button 有 loading 状态了。
close: https://github.com/keiko233/clash-nyanpasu/issues/80
=> feat: add rules providers page and fix issues

backend/tauri/src/core/storage.rs
related: https://github.com/hyperledger/besu/issues/4639 https://github.com/hyperledger/besu/issues/3719 https://github.com/hyperledger/besu/pull/3720
fix: https://github.com/keiko233/clash-nyanpasu/issues/190
手动对乐观事务 Busy 的情况进行重试似乎不太经济。因此直接使用普通事务模式。
=> fix(rocksdb): resource busy issue

.github/workflows/ci.yml, .github/workflows/dev.yaml, .github/workflows/macos-aarch64.yaml, .github/workflows/release.yml
fix: https://github.com/keiko233/clash-nyanpasu/issues/210
=> fix(ci): pin rust version to 1.74.1

backend/tauri/src/core/core.rs, rust-toolchain.toml
Start this App with `enable_tun` will be no response
Related issue: https://github.com/tauri-apps/tauri/pull/8539
Only do `recv` once manually without waiting for more
=> fix(macos): enable_tun block the process

.github/workflows/daily.yml
=> fix(ci): should generate manifest in dev for compatible with <=1.4.3

.github/workflows/release.yml, backend/tauri/src/cmds.rs, backend/tauri/src/main.rs, scripts/updater.ts, src/hooks/use-notification.ts, src/services/cmds.ts
close https://github.com/keiko233/clash-nyanpasu/issues/314
=> fix(portable): do not use system notification api while app is portable

src/components/connection/connection-table.tsx
Use valueFormatter to only change the way data is displayed, without altering the data itself, so that columns can be sorted by numerical comparison.
For example, `200` and `1000` would be displayed as the strings `200 B` and `1 KB`, but still compared numerically as `200 < 1000`, rather than by the dictionary order of the strings.
close #336
=> fix: sort connection in numerical comparison for Download, DL Speed, etc

backend/tauri/src/main.rs, backend/tauri/src/utils/init/logging.rs, src/pages/_layout.tsx, src/pages/profiles.tsx
fix schema not working for new opening and dialog and dialog not showing with certain route
=> fix(custom-schema): fix custom schema

backend/Cargo.lock, backend/tauri/Cargo.toml, backend/tauri/src/cmds.rs, backend/tauri/src/config/clash.rs, backend/tauri/src/config/clash/mod.rs, backend/tauri/src/config/mod.rs, backend/tauri/src/config/nyanpasu/clash_strategy.rs, backend/tauri/src/config/nyanpasu/mod.rs, backend/tauri/src/core/clash/core.rs, backend/tauri/src/core/updater.rs, backend/tauri/src/core/win_service.rs, backend/tauri/src/enhance/chain.rs, backend/tauri/src/feat.rs, backend/tauri/src/utils/help.rs, backend/tauri/src/utils/init/logging.rs, backend/tauri/src/utils/resolve.rs, renovate.json, src/components/layout/update-button.tsx, src/components/setting/mods/controller-viewer.tsx, src/components/setting/setting-verge.tsx, src/services/types.d.ts
Close https://github.com/LibNyanpasu/clash-nyanpasu/issues/242
TODO:
将 AllowFallback、Fixed 所需的 Port 分离到 app config 中，避免造成歧义。
=> feat(clash): add default core secret and impl port checker before clash start

src/components/setting/setting-verge.tsx, src/services/cmds.ts, src/utils/index.ts
Close https://github.com/LibNyanpasu/clash-nyanpasu/issues/589
=> fix(cmds): `path` in changing app dir call

manifest/version.json, scripts/check.ts, scripts/generate-latest-version.ts
This program can only be run on AMD64 processors with v3 microarchitecture support.
#16
=> fix: mac x64 mihomo使用compatible内核

frontend/nyanpasu/src/locales/zh-CN.json
I remember noticing it several times, but forgetting to fix it in previous PRs.
=> chore(i18n): fix a typesetting in zh-cn

backend/tauri/src/enhance/advice.rs
当前在tun的enable字段未设置或为false时会触发TUN权限警告 看上去貌似是判断写反了...?
以及这个警告会阻止Clash启动 在开机自启时会导致代理断网 感觉这条应该额外拿出来发个Issue 不会修(
=> fix: show TUN permission warning only when TUN is enabled

.github/workflows/deps-build-linux.yaml
Fix the issue where GTK icon cache update fails on Linux (related to Issue #3424).  
The main binary name contained spaces (e.g., "Clash Nyanpasu"), which caused:
- GTK icon cache update failure  
- hicolor icon theme errors  
- DEB/RPM package desktop icon not displaying correctly  
Root cause: GTK cannot properly handle icon file names containing spaces.
- Rename icon files during workflow build:  
`Clash Nyanpasu.png -> clash_nyanpasu.png`  
- Update the `Icon=` field in the `.desktop` file  
- Refresh GTK icon cache  
- Apply to all Linux build architectures (x86_64 + cross builds)
- No impact on Windows/macOS builds  
- Backward-compatible, no changes needed for user configuration  
---
修复 Linux 下 GTK 图标缓存更新失败的问题。
应用程序二进制文件名包含空格（如 "Clash Nyanpasu"），会导致：
- GTK 图标缓存更新失败  
- hicolor …
=> fix(linux): rename GTK icons to avoid cache update failure

frontend/nyanpasu/src/components/profiles/profile-monaco-viewer.tsx, frontend/nyanpasu/src/components/profiles/script-dialog.tsx, frontend/nyanpasu/src/services/monaco.ts
**Summary:**  
This PR fixes two key issues in the script editing UI. #3611 
**1. Draggable window**
- The script editor window can now be dragged by its title bar using the `data-tauri-drag-region` attribute in the `ScriptDialog` component.
**2. URL opening functionality**
- URLs in scripts are now clickable and open in the system default browser via Tauri’s `openThat` function.
**Improvements include:**
- Importing Monaco’s links contribution
- Enhanced URL regex detection
- Cursor changes to pointer on hover
- Custom link provider for JavaScript, Lua, and YAML
**Note:**
- The main fix for URL opening is using Tauri’s API instead of `window.open`, which may not work correctly in Tauri apps due to security restrictions.
**Result:**
- Users can drag the script window via the title bar.
- …
=> fix(script-ui): enable draggable window and proper URL opening in Monaco #3611

backend/tauri/src/cmds/migrate.rs, backend/tauri/src/lib.rs, backend/tauri/src/utils/dirs.rs, backend/tauri/src/utils/init/mod.rs, backend/tauri/src/utils/mod.rs, backend/tauri/src/utils/winreg.rs, backend/tauri/src/utils/winreg_test.rs
- Fixes the issue where multiple Windows users cannot open the GUI simultaneously (singleton lock conflicts across users)
- Implements a consistent, cross-platform singleton detection scoped by user/configuration
- Improves error handling and log output
1. **Windows singleton lock was system-wide**
- Changed to include user/config directory scope, supporting portable mode and custom AppDir
- File: `backend/tauri/src/utils/dirs.rs`
2. **Non-Windows unwrap could panic**
- Removed unwrap, propagate `Result` instead
3. **Singleton semantics inconsistent across platforms**
- Windows: named mutex with config directory hash
- Non-Windows: lock file path in config directory
- Files: `backend/tauri/src/utils/dirs.rs`, `backend/tauri/src/utils/init/mod.rs`
4. **Portable mode & custom AppDir not …
=> fix(singleton): isolate Windows singleton per user/config and unify cross-platform behavior

.gitignore, backend/Cargo.lock, backend/boa_utils/src/module/http.rs, backend/nyanpasu-egui/src/utils/svg.rs, backend/tauri/Cargo.toml, backend/tauri/src/config/nyanpasu/mod.rs, backend/tauri/src/core/migration/units/unit_200.rs, backend/tauri/src/core/tasks/storage.rs, backend/tauri/src/core/tray/mod.rs, backend/tauri/src/event_handler/mod.rs, backend/tauri/src/event_handler/widget.rs, backend/tauri/src/logging/manager.rs, backend/tauri/src/utils/help.rs
- 修复 issue #3038 
- 用户开启「局域网连接」后，应用重启会重置为关闭  
- **根因**：`clash-guard-overrides.yaml` 读取失败时直接回退到默认配置 (`allow-lan: false`)，导致用户设置丢失  
实现 **智能配置恢复机制**，避免设置丢失，包含三层降级策略：  
1. 优先从 **备份文件** 恢复  
2. 若失败，尝试 **部分配置恢复**（提取 `allow-lan`, `mode`, `log-level`, `mixed-port`, `ipv6` 等关键字段）  
3. 最后才使用默认模板  
- **自动备份**：保存配置时生成 `clash-guard-overrides.backup.yaml`  
- **部分恢复**：损坏文件仍可提取关键设置  
- **日志增强**：详细记录恢复过程（成功/部分/失败）  
- **手动恢复接口**：新增 IPC 命令 `recover_clash_config_from_backup` 和 `get_clash_config_status`  
- **完整测试**：新增 8 个测试用例，覆盖各种恢复场景  
- ✅ 向后兼容，正常场景用户无感知  
- ✅ 跨平台支持（Windows/macOS/Linux）  
- ⏱ 启动恢复检测开销 < 10ms，仅在失败时触发  
- 💾 存储开销极低（单个备份文件 ~1KB）
=> fix(config): persist LAN connection setting with smart recovery

frontend/nyanpasu/src/components/app/modules/route-list-item.tsx
为 `RouteListItem` 组件新增 tooltip 功能，解决仅图标导航模式下无法显示标签的问题。
1. 从 `@mui/material` 导入 `Tooltip`
2. 将 `ListItemButton` 提取到变量 `listItemButton`，便于条件包裹
3. 当 `onlyIcon = true` 时，用 `Tooltip` 包裹 `ListItemButton`
4. tooltip 内容使用现有翻译 key
- **仅图标模式**：悬停图标显示对应标签的 tooltip
- **完整模式**：正常显示文本，无 tooltip
用户启用“图标导航栏”后，悬停侧边栏图标即可看到提示标签，提升可访问性和可用性，同时保持现有功能不变。
=> feat: tooltips display

frontend/nyanpasu/src/components/profiles/modules/chain-item.tsx, frontend/nyanpasu/src/components/profiles/modules/side-chain.tsx, frontend/nyanpasu/src/components/profiles/profile-side.tsx, frontend/nyanpasu/src/locales/zh-CN.json
UI 展示所有链配置时，没有区分全局链和个人配置（本地链），导致用户无法清晰判断每条链所属的上下文。
- **增强数据传递**：修改 `SideChain` 组件，为每个 `ChainItem` 提供额外的上下文信息。
- **视觉标识**：在 `ChainItem` 上增加徽章，清楚标示链是全局链还是本地链。
- **保持核心功能**：保留原有的选中高亮机制，同时增加新的视觉区分。
- 消除全局链与本地链的混淆。
- 提供明确的视觉反馈，直观显示链的上下文。
- 保持功能完整，同时提升用户体验清晰度。
- 用户可一眼区分全局链和本地链。
---
https://github.com/user-attachments/assets/8e36ebcb-b799-4c00-a83e-43de9723c295
=> fix: proxy chain ui

backend/tauri/src/enhance/mod.rs
**描述:**  
该 PR 实现了 Clash Nyanpasu 配置增强系统中代理组对 `include-all: true` 字段的支持。带有该字段的代理组将自动包含配置中所有可用代理（来自 `proxies` 和 `proxy-providers`），同时保留组内已有代理。处理完成后，`include-all` 字段会被移除以避免冲突。
**实现细节:**
1. 新增 `use_include_all_proxy_groups` 函数，用于处理 `include-all` 代理组。
2. 将该函数集成到增强流水线中（在 `tun` 处理后，缓存处理前调用）。
3. 支持从 `proxies` 和 `proxy-providers` 收集代理。
4. 保留不在“所有代理”集合中的已有代理。
5. 处理完成后移除 `include-all` 字段。
**配置示例:**
```yaml
proxy-groups:
- name: GLOBAL
type: select
include-all: true
proxies:
- DIRECT
```
该配置会自动将 `GLOBAL` 组填充所有可用代理，同时保留 `DIRECT`。
**测试:**
- 验证了从 `proxies` 和 `proxy-providers` 正确收集代理名称。
- 确认 `include-all` 字段处理正确。
- 确认保留已有代理。
- 检查处理完成后移除了 `include-all` 字段。
**影响:**
- 用户现在可以轻松配置代理组以自动包含所有可用代理。
- 提高了配置灵活性，减少了手动维护代理列表的工作量。
=> feat(enhance): add include-all field support for proxy groups
